---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lew.
--- DateTime: 2020/6/2 15:45
---
local SURS = { "A", "B1", "B2", "C", "D1", "E", "G1", "H", "I", "L", "P", "S", "U1", "U2", "V1", "V2", "X" }
local NAVPBASES = { "A1", "B1", "B2", "B3", "B4", "B5", "B6", "C1", "C2", "C3", "C4", "D1", "D2", "D3", "D4", "L1", "O1", "O2", "O3", "O4", "S1", "S2", "T1", "T2" }
local NAVCS = { "A", "B", "C", "D", "F", "G", "I", "K", "L", "O", "T", "W", "X" }
local DLCS ={ "J1", "J2", "J3", "J4", "J5", "J6", "J7" }
local COMMS = { "E1", "E2", "E3", "H", "M1", "M2", "M3", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9", "U", "V", "Y" }

function surveillance(obj)
    local ori = obj.value
    local res = ""
    local isfirst = true
    for i, v in ipairs(SURS) do
        local ind = string.find(ori, v)
        if (ind)
        then
            if (isfirst)
            then
                isfirst = false
                res = res .. "<fx:surveillanceCapabilityCode>"
            else
                res = res .. " "
            end
            res = res .. v
        end
    end
    if (not isfirst)
    then
        res = res .. "</fx:surveillanceCapabilityCode>"
    end
    return res
end

function navigationperformanceBasedCode(obj)
    local ori = obj.value
    local res = ""
    local isfirst = true
    for i, v in ipairs(NAVPBASES) do
        local ind = string.find(ori, v)
        if (ind)
        then
            if (isfirst)
            then
                isfirst = false
                res = "<fx:performanceBasedCode>"
            else
                res = res .. " "
            end
            res = res .. v
        end
    end
    if (not isfirst)
    then
        res = res .. "</fx:performanceBasedCode>"
    end
    return res
end

function navigationCapabilityCode(obj)
    local ori = obj.value
    local res = ""
    local isfirst = true
    for i, v in ipairs(NAVCS) do
        local ind = string.find(ori, v)
        if (ind) then
            if (isfirst) then
                isfirst = false
                res = "<fx:navigationCapabilityCode>"
            else
                res = res .. " "
            end
            res = res .. v
        end
    end
    if (not isfirst) then
        res = res .. "</fx:navigationCapabilityCode>"
    end
    return res
end

function datalinkCommunication(obj)
    local ori = obj.value
    local res = ""
    local isfirst = true
    for i, v in ipairs(DLCS) do
        local ind = string.find(ori, v)
        if (ind)
        then
            if (isfirst)
            then
                isfirst = false
                res = "<fx:datalinkCommunicationCapabilityCode>"
            else
                res = res .. " "
            end
            res = res .. v
        end
    end
    if (not isfirst)
    then
        res = res .. "</fx:datalinkCommunicationCapabilityCode>"
    end
    return res
end

function communication(obj)
    local ori = obj.value
    local res = ""
    local isfirst = true
    for i, v in ipairs(COMMS) do
        local ind = string.find(ori, v)
        if (ind)
        then
            if (isfirst)
            then
                isfirst = false
                res = "<fx:communicationCapabilityCode>"
            else
                res = res .. " "
            end
            res = res .. v
        end
    end
    if (not isfirst)
    then
        res = res .. "</fx:communicationCapabilityCode>"
    end
    return res
end
