---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lew.
--- DateTime: 2020/5/11 15:29
---
---
v="0730"
v=tonumber(v)
print(v)
print("a" .. v .. "cc")
local REG_ROUTE = '[^P]+[0-9]+'
function trim1(s)
    return (s:gsub("^%s*(.-)%s*$", "%1"))
end
print(trim1("lew"))
print(trim1("lew   "))
print(trim1("    lew   "))
print(trim1("   lew"))
print(trim1("   le w  "))


str = "运DDD大大1D2C"
str,index = string.gsub(str, "[^A-Z0-9]", "")
print(string.sub(str,1,4))
--util = require("util")
--all = require("all")
--route = "R34G"
--print(isRoute('P234'))
--print(isRoute('A234A'))
--print(isRoute('AC234A'))
--print(isRoute('AD234'))
--print(isRoute('FANS-4'))
--a, b = string.find(route, REG_ROUTE)
--print(a)
--if a == 1 and b == string.len(route)
--then
--    print(true)
--else
--    print(false)
--end
--print(b)
--for c = 10, 1, -1 do
--    print(c)
--    local c = c + 2
--end
--8040N13023W
local lonval = "13023"
local int = string.sub(lonval, 1, 3)
local deci = string.sub(lonval, 4, 5)
int = tonumber(int)
deci = tonumber(deci) / 60 + int

print(string.format("%.4f", deci))

