---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lew.
--- DateTime: 2020/5/11 12:09
---
local _util = {}
function _util.starts(String, Start)
    return string.sub(String, 1, string.len(Start)) == Start
end

function _util.ends(String, End)
    return string.sub(String, string.len(String) - string.len(End) + 1, string.len(String)) == End
end

function _util.fullMatch(String, Regex)
    local s_start, s_stop = string.find(String, Regex)
    if s_start == 1 and s_stop == string.len(String)
    then
        return true
    else
        return false
    end

end

function _util.isempty(s)
    return s == nil or s == ''
end

function _util.inTable(value, table)
    if (table == nil)
    then
        return false
    end
    for i, v in pairs(table) do
        --if (type(v) == "table")
        --then
        --    if (inTable(value, v))
        --    then
        --        return true
        --    end
        --end
        if (value == v)
        then
            return true
        end
    end
    return false
end

-- date format is 'yyyy-mm-dd HH:MI'
function _util.getDate(date)
    if (date == nil) then
        return nil
    elseif string.len(date) == 16 then
        local retable = {}
        retable.year = string.sub(date, 1, 4)
        retable.month = string.sub(date, 6, 7)
        retable.day = string.sub(date, 9, 10)
        retable.hour = string.sub(date, 12, 13)
        retable.min = string.sub(date, 15, 16)
        return retable
    else
        return nil
    end
end

return _util
--obj = { a = 100, d = "hello", "Suanday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" }--创建时设置属性
--print(obj.a)
--print(obj["b"])
--print(#obj)

