sso:
  server: http://192.168.204.67:8085
  logout:
    path: /logout
  excluded:
    paths: /**/*.css, /**/*.js, /**/*.png, /**/*.jpg,/static/**,/user/update,/sso/**,/,/fixmlogic/{version}/uploadValidateFile
zuul:
  # 网关地址（用于更新微服务信息）默认为''
  url: http://127.0.0.1:9000
task:
  # 后台任务周期cron表达式（）默认为 0 */5 * * * * 每五分钟轮询一次
  cron: 0 */5 * * * *
server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://192.168.243.87:3306?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: adccaims2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
logging:
  config: classpath:logback.xml
