sso:
  server: http://192.168.204.67:8085
  logout:
    path: /logout
  excluded:
    paths: /**/*.css, /**/*.js, /**/*.png, /**/*.jpg,/static/**,/user/update,/**/*
server:
  port: 9005
spring:
  datasource:
    url: jdbc:mysql://192.168.243.87:3306/micro-service-manage?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: adccaims2019
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 192.168.243.87
